stages:
  - test
  - build

variables:
  DEBUG: "1"

#
# test
#


lint:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y python3-black
  script:
    - black -v --diff --color --check qubesbuilder

mypy:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y python3-mypy python3-pip
    - sudo python3 -m pip install types-PyYAML
  script:
    - mypy --install-types --non-interactive --junit-xml mypy.xml qubesbuilder
  artifacts:
    reports:
      junit: mypy.xml

shellcheck:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y ShellCheck git
  script:
    - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
  allow_failure: true

pytest:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - docker
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/app.xml
      cobertura: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  script:
    - docker pull fedora:latest
    - docker-compose -f tests/docker-compose.yml build pytest
    - docker-compose -f tests/docker-compose.yml run pytest

#
# build
#

.build_test_job:
  stage: build
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - docker
  artifacts:
    paths:
      - artifacts
  script:
    - docker pull fedora:latest
    - docker-compose -f tests/docker-compose.yml build base "${CI_JOB_NAME}"
    - docker-compose -f tests/docker-compose.yml run "${CI_JOB_NAME}"

host-fc32:
  extends: .build_test_job

vm-fc35:
  extends: .build_test_job

vm-bullseye:
  extends: .build_test_job
