stages:
  - test

variables:
  DEBUG: "1"

lint:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y python3-black
  script:
    - black -v --diff --color --check qubesbuilder

mypy:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y python3-mypy python3-pip
    - sudo python3 -m pip install types-PyYAML
  script:
    - mypy --install-types --non-interactive --junit-xml mypy.xml qubesbuilder
  artifacts:
    reports:
      junit: mypy.xml

shellcheck:
  stage: test
  image: fedora:latest
  before_script:
    - sudo dnf install -y ShellCheck git
  script:
    - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
  allow_failure: true

tests:
  stage: test
  image: docker/compose:latest
  services:
    - docker:dind
  tags:
    - docker
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/app.xml
      cobertura: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  script:
    - docker pull fedora:latest
    - docker-compose -f tests/docker-compose.yml build test
    - docker-compose -f tests/docker-compose.yml run test
  allow_failure: true
