#
# Qubes Builder Gitlab CI
#

stages:
  - test
  - package
  - template

variables:
  DEBUG: "1"

#
# test
#

lint:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-black
  script:
    - black -v --diff --color --check qubesbuilder

mypy:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-mypy python3-pip
    - sudo python3 -m pip install types-PyYAML types-python-dateutil
  script:
    - mypy --install-types --non-interactive --junit-xml mypy.xml qubesbuilder
  artifacts:
    reports:
      junit: mypy.xml

shellcheck:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y ShellCheck git
  script:
    - shellcheck -x -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))

pytest:
  stage: test
  tags:
    - qubes
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/qubesbuilder.xml
      coverage_report:
        coverage_format: cobertura
        path: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  variables:
    PYTHONPATH: .
  before_script:
    - sudo dnf install -y python3-pathspec
  script:
    - docker build -f dockerfiles/fedora.Dockerfile -t qubes-builder-fedora .
    - pytest-3 -v --color=yes --cov qubesbuilder --cov-report term --cov-report html:artifacts/htmlcov --cov-report xml:artifacts/coverage.xml --junitxml=artifacts/qubesbuilder.xml tests/

#
# build job skeleton
#

.component_docker_job:
  stage: package
  tags:
    - vm
  artifacts:
    paths:
      - artifacts
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
    - docker pull fepitre/qubes-builder-fedora:latest
    - docker tag fepitre/qubes-builder-fedora:latest qubes-builder-fedora:latest
  #    - docker build -f dockerfiles/fedora.Dockerfile -t qubes-builder-fedora .
  script:
    - cp tests/builder-ci.yml builder.yml
    - ./qb -d "${CI_JOB_NAME#docker-}" package all

.component_podman_job:
  stage: package
  tags:
    - vm
  artifacts:
    paths:
      - artifacts
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
    - systemctl --user start podman
    - podman pull docker.io/fepitre/qubes-builder-fedora:latest
    - podman tag docker.io/fepitre/qubes-builder-fedora:latest qubes-builder-fedora:latest
  #    - podman build -f dockerfiles/fedora.Dockerfile -t qubes-builder-fedora .
  script:
    - cp tests/builder-ci.yml builder.yml
    - sed -i 's/docker/podman/' builder.yml
    - ./qb -d "${CI_JOB_NAME#podman-}" package all

.component_qubes_job:
  stage: package
  tags:
    - qubes
  artifacts:
    paths:
      - artifacts
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
  script:
    - cp tests/builder-ci.yml builder.yml
    - sed -i 's/docker/qubes/' builder.yml
    - 'sed -i ''s|image:.*|dispvm: "qubes-builder-dvm"|'' builder.yml'
    - ./qb -d "${CI_JOB_NAME#qubes-}" package all

.template_qubes_job:
  stage: template
  tags:
    - qubes
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
  script:
    - cp tests/builder-ci.yml builder.yml
    - sed -i 's/docker/qubes/' builder.yml
    - 'sed -i ''s|image:.*|dispvm: "qubes-builder-dvm"|'' builder.yml'
    - ./qb -t "${CI_JOB_NAME#qubes-template-}" template all

#
# Components
#

# Podman executor

podman-host-fc32:
  extends: .component_podman_job

podman-vm-fc35:
  extends: .component_podman_job

podman-vm-centos-stream8:
  extends: .component_podman_job

#podman-vm-bullseye:
#  extends: .component_podman_job

# Docker executor

docker-host-fc32:
  extends: .component_docker_job

docker-vm-fc35:
  extends: .component_docker_job

docker-vm-centos-stream8:
  extends: .component_docker_job

docker-vm-bullseye:
  extends: .component_docker_job

# Qubes executor

qubes-host-fc32:
  extends: .component_qubes_job

qubes-vm-fc35:
  extends: .component_qubes_job

qubes-vm-centos-stream8:
  extends: .component_qubes_job

qubes-vm-bullseye:
  extends: .component_qubes_job

#
# Templates
#

qubes-template-fedora-35-xfce:
  extends: .template_qubes_job

qubes-template-centos-stream-8:
  extends: .template_qubes_job

qubes-template-debian-11:
  extends: .template_qubes_job

qubes-template-whonix-gateway-16:
  extends: .template_qubes_job

qubes-template-whonix-workstation-16:
  extends: .template_qubes_job
