#
# Qubes Builder Gitlab CI
#

stages:
  - test
  - build

variables:
  DEBUG: "1"

#
# test
#


lint:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-black
  script:
    - black -v --diff --color --check qubesbuilder

mypy:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y python3-mypy python3-pip
    - sudo python3 -m pip install types-PyYAML
  script:
    - mypy --install-types --non-interactive --junit-xml mypy.xml qubesbuilder
  artifacts:
    reports:
      junit: mypy.xml

shellcheck:
  stage: test
  image: fedora:latest
  tags:
    - docker
  before_script:
    - sudo dnf install -y ShellCheck git
  script:
    - shellcheck -e SC1117 $(grep -l '^#!/bin/\(ba\)\?sh' $(git ls-files))
  allow_failure: true

pytest:
  stage: test
  tags:
    - qubes
  artifacts:
    paths:
      - artifacts/htmlcov/
    reports:
      junit: artifacts/app.xml
      cobertura: artifacts/coverage.xml
  coverage: '/TOTAL.*\s(\d+)%/'
  variables:
    PYTHONPATH: .
  script:
    - docker build -f dockerfiles/fedora.Dockerfile -t qubes-builder-fedora .
    - pytest-3 -v --color=yes --cov qubesbuilder --cov-report term --cov-report html:artifacts/htmlcov --cov-report xml:artifacts/coverage.xml --junitxml=artifacts/qubesbuilder.xml tests/

#
# build job skeleton
#

.component_container_job:
  stage: test
  tags:
    - vm
  artifacts:
    paths:
      - artifacts
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
    - docker build -f dockerfiles/fedora.Dockerfile -t qubes-builder-fedora .
  script:
    - cp tests/builder-ci.yml builder.yml
    - ./qb -d "${CI_JOB_NAME#container-}" qubes

.component_qubes_job:
  stage: test
  tags:
    - qubes
  artifacts:
    paths:
      - artifacts
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
  script:
    - cp tests/builder-ci.yml builder.yml
    - sed -i 's/docker/qubes/' builder.yml
    - "sed -i 's|image:.*|dispvm: \"qubes-builder-dvm\"|' builder.yml"
    - ./qb -d "${CI_JOB_NAME#qubes-}" qubes

.template_qubes_job:
  stage: test
  tags:
    - qubes
  before_script:
    - cp -r tests/gnupg ~/.gnupg
    - chmod 700 ~/.gnupg
  script:
    - cp tests/builder-ci.yml builder.yml
    - sed -i 's/docker/qubes/' builder.yml
    - "sed -i 's|image:.*|dispvm: \"qubes-builder-dvm\"|' builder.yml"
    - ./qb -t "${CI_JOB_NAME#qubes-}" template

#
# Container executor
#

container-host-fc32:
  extends: .component_container_job

container-vm-fc35:
  extends: .component_container_job

container-vm-bullseye:
  extends: .component_container_job

#
# Qubes executor
#

qubes-host-fc32:
  extends: .component_qubes_job

qubes-vm-fc35:
  extends: .component_qubes_job

qubes-vm-bullseye:
  extends: .component_qubes_job

qubes-fedora-35-xfce:
  extends: .template_qubes_job
