git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: master

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.2

distributions:
  - host-fc32
  - vm-bullseye
  - vm-fc36

templates:
  - fedora-36:
      dist: fc36
  - debian-11:
      dist: bullseye
      options:
        - standard
        - firmware
  - whonix-gateway-16:
      dist: bullseye
      flavor: whonix-gateway
      options:
        - minimal
        - no-recommends
  - whonix-workstation-16:
      dist: bullseye
      flavor: whonix-workstation
      options:
        - minimal
        - no-recommends

components:
  - vmm-xen:
      branch: xen-4.14
  - core-libvirt
  - core-vchan-xen
  - core-qubesdb
  - core-qrexec
  - linux-utils
  - python-xcffib
  - python-objgraph
  - python-u2flib-host
  - python-qasync
  - python-panflute
  - rpm-oxide:
      branch: main
  - core-admin
  - core-admin-client
  - core-admin-addon-whonix
  - core-admin-linux
  - core-agent-linux
  - intel-microcode
  - linux-firmware
  - linux-kernel:
      branch: stable-5.15
      timeout: 21600
  - linux-kernel-latest:
      url: https://github.com/QubesOS/qubes-linux-kernel
      branch: master
      timeout: 21600
  - artwork
  - grub2
  - grub2-theme
  - gui-common
  - gui-daemon
  - gui-agent-linux
  - seabios
  - vmm-xen-stubdom-legacy
  - vmm-xen-stubdom-linux
  - app-linux-split-gpg
  - app-linux-split-gpg2
  - app-thunderbird
  - app-linux-pdf-converter
  - app-linux-img-converter
  - app-linux-input-proxy
  - app-linux-usb-proxy
  - app-linux-snapd-helper
  - app-shutdown-idle
  - app-yubikey
  - app-u2f
  - screenshot-helper
  - mgmt-salt
  - mgmt-salt-base
  - mgmt-salt-base-topd
  - mgmt-salt-base-config
  - mgmt-salt-dom0-qvm
  - mgmt-salt-dom0-virtual-machines
  - mgmt-salt-dom0-update
  - infrastructure
  - repo-templates
  - meta-packages
  - manager
  - desktop-linux-common
  - desktop-linux-kde
  - desktop-linux-xfce4
  - desktop-linux-xfce4-xfwm4
  - desktop-linux-i3
  - desktop-linux-i3-settings-qubes
  - desktop-linux-awesome
  - desktop-linux-manager
  - grubby-dummy
  - dummy-psu
  - dummy-backlight
  - xorg-x11-drv-intel
  - xorg-x11-drv-amdgpu:
      branch: main
  - linux-pvgrub2
  - linux-gbulb
  - linux-scrypt
  - xdotool
  - alsa-lib:
      branch: main
  - alsa-utils:
      branch: main
  - alsa-sof-firmware:
      branch: main
  - lvm2
  - qubes-release
  - pykickstart
  - blivet
  - lorax
  - lorax-templates
  - anaconda
  - anaconda-addon
  - efitools:
      branch: main
  - sbsigntools:
      branch: main
  - tpm2-tss:
      branch: main
  - tpm2-tools:
      branch: main
  - tpm-extra
  - trousers-changer
  - antievilmaid
  - xscreensaver
  - remote-support
  - windows-tools-cross


#executor:
#  type: docker
#  options:
#    image: "qubes-builder-fedora:latest"

executor:
  type: qubes
  options:
    dispvm: "qubes-builder-dvm"

stages:
  - fetch
  - prep
  - build
  - post
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local
